# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('sku', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('root_sku', models.CharField(max_length=16)),
                ('old_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('material_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('sub_category', models.CharField(max_length=64)),
                ('collection', models.CharField(max_length=72)),
                ('sub_collection', models.CharField(blank=True, max_length=72, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('variations', models.CharField(blank=True, max_length=400, null=True)),
                ('variation_group', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
