# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sku', models.CharField(max_length=16)),
                ('item_name', models.CharField(max_length=16)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('main_image_url', models.CharField(max_length=200)),
                ('main_image_path', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=16)),
                ('collection', models.CharField(max_length=72)),
                ('sub_collection', models.CharField(max_length=72)),
            ],
        ),
    ]
