# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('original_image_name', models.CharField(max_length=16, null=True, unique=True)),
                ('source_identifier', models.CharField(blank=True, max_length=16, null=True)),
                ('sku', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('root_sku', models.CharField(max_length=16, null=True)),
                ('old_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('image_name', models.CharField(max_length=128)),
                ('image_height', models.IntegerField()),
                ('image_width', models.IntegerField()),
                ('short_title', models.CharField(blank=True, max_length=200, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=32, null=True)),
                ('product_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('photographer', models.CharField(blank=True, max_length=72, null=True)),
                ('artist', models.CharField(blank=True, max_length=72, null=True)),
                ('medium', models.CharField(blank=True, max_length=72, null=True)),
                ('format', models.CharField(blank=True, max_length=72, null=True)),
                ('reproduction_number', models.CharField(blank=True, max_length=72, null=True)),
                ('material_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('sub_category', models.CharField(max_length=64)),
                ('collection', models.CharField(max_length=72)),
                ('sub_collection', models.CharField(blank=True, max_length=72, null=True)),
                ('image_folder', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=400, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('rights', models.CharField(blank=True, max_length=2000, null=True)),
                ('original_keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('additional_keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('additional_keywords_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
