# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sub_collection',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
