# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='old_sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
