# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='height',
            new_name='image_height',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='width',
            new_name='image_width',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='info',
        ),
        migrations.RemoveField(
            model_name='image',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='variation_group',
        ),
        migrations.RemoveField(
            model_name='image',
            name='variations',
        ),
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='identifier',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='medium',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_image_name',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='photographer',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='reproduction_number',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='short_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
