# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_auto_20180320_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='root_sku',
            field=models.CharField(max_length=16),
        ),
    ]
