# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_auto_20180420_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='identifier',
            new_name='source_identifier',
        ),
        migrations.AddField(
            model_name='image',
            name='additional_keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='additional_keywords_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='rights',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='root_sku',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
