# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_auto_20180306_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
