# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0003_auto_20180320_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='sku',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
