# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_auto_20180306_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
