# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0005_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='type',
        ),
    ]
