# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=64)),
                ('catalog_number', models.CharField(max_length=200)),
                ('size_name', models.CharField(max_length=200)),
                ('variation_theme', models.CharField(max_length=200)),
                ('product_tax_code', models.CharField(max_length=200)),
                ('bullet1', models.CharField(max_length=200)),
                ('bullet2', models.CharField(max_length=200)),
                ('bullet3', models.CharField(max_length=200)),
                ('bullet4', models.CharField(max_length=200)),
                ('bullet5', models.CharField(max_length=200)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Images.Image')),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bullet', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
