# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bullet', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=200)),
                ('size_name', models.CharField(max_length=200)),
                ('variation_theme', models.CharField(max_length=200)),
                ('product_tax_code', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
                ('bullet1', models.CharField(max_length=200)),
                ('bullet2', models.CharField(max_length=200)),
                ('bullet3', models.CharField(max_length=200)),
                ('bullet4', models.CharField(max_length=200)),
                ('bullet5', models.CharField(max_length=200)),
            ],
        ),
    ]
