# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_variation',
            name='check_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazon_variation',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
