# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_variation',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
