# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='parent_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Images.Image'),
        ),
    ]
