# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0002_auto_20180320_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='item_sku',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
