# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_auto_20180321_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='product_description',
            field=models.CharField(max_length=5000),
        ),
    ]
