# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_auto_20180318_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='parent_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Images.Image'),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='product_tax_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='variation_theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
