# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_auto_20180319_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='currency',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
