# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 11:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_auto_20180321_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
