# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0005_auto_20180321_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
