# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0006_auto_20180321_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
