# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0007_auto_20180321_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_variation',
            name='is_orphan',
            field=models.BooleanField(default=True),
        ),
    ]
