# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0008_amazon_variation_is_orphan'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_variation',
            name='check_unicode',
            field=models.BooleanField(default=False),
        ),
    ]
