# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0009_amazon_variation_check_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_variation',
            name='check_bullets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='bullet5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amazon_variation',
            name='product_description',
            field=models.CharField(max_length=2000),
        ),
    ]
