# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-23 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0010_auto_20180323_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_variation',
            name='keywords',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
